### ISSUE TITLE
Minor update to the readme

### ISSUE THREAD

**Issue by zepumph** [project-beholder/beholder-detection#1]
From initial investigation, I had a couple of thoughts that may help the README for this project.

It would be nice to explain a bit about the specifics of what "marker detection" this library supports. For example, mentioning "aruco" as well as the flavor that is supported ("Original ArUco"). That would be helpful. Also perhaps an optional link to https://chev.me/arucogen/ for those that don't know how to find them. I didn't remember the right buzz words from last march, and I tried finding them by googling "fiducial marker" but forgot about needing the ArUco type.

**Comment by Petroochio** [comment]
Resolved in 1.1.9
